pipeline {
   agent { label 'aws-ec2' }
    stages {
        stage('Build') {
            steps {
                sh 'df -h'
            }
        },
         stage('test') {
            steps {
                sh 'du -sh'
            }
        },
         stage('deploy') {
            steps {
                sh 'whoami'
            }
        }

    }
}

